import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Source_Sans_3 } from "next/font/google";
import { DrawerUser } from "@/components/common/DrawerUser";
import { HydrationLoader } from "@/providers/hydration-loader";
import RservationWatcher from "@/containers/reservation-watcher/ReservationWatcher";
// import { AuthGuard } from "./containers/common/AuthGuard";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const sourseSans = Source_Sans_3({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-source-sans-3",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` scrollbar-modern ${sourseSans.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans text-white antialiased bg-colors-primary-hard font-medium`}
      >
        <HydrationLoader>
          <DrawerUser />
          <RservationWatcher/>
          {/* <AuthGuard  fallback={<><p>...cargando auth</p></>}> */}
            
          {children}
          {/* </AuthGuard> */}
        </HydrationLoader>
      </body>
    </html>
  );
}
